name: QA

on:
  workflow_dispatch:
  push:
  pull_request:

env:
  BUILD_PATH: "."

jobs:
  qa:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install
        working-directory: ${{ env.BUILD_PATH }}

      - name: Build with Astro
        run: bun run build
        working-directory: ${{ env.BUILD_PATH }}

      - name: Run tests
        run: bun run test
        working-directory: ${{ env.BUILD_PATH }}

      - name: Run lint
        run: bun run lint
        working-directory: ${{ env.BUILD_PATH }}

      - name: Run format check
        run: bun run format:check
        working-directory: ${{ env.BUILD_PATH }}
